### ISSUE TITLE
TODO Ideas:

### ISSUE THREAD

**Issue by aglushkov** [aglushkov/jat#34]
- [ ] Allow to skip parameters validation via config
- [ ] Add classic response adapter
- [ ] Allow to redefine final id and type using object and context
- [ ] Add yarddoc [DOC]
- [ ] Add polymorphic examples [DOC]

**Comment by aglushkov** [comment]
Freeze input args?

```ruby
    # :reek:DuplicateMethodCall
    # :reek:FeatureEnvy
    # :reek:TooManyStatements
    def dup_freeze(params)
      case params
      when Hash
        params.transform_values { |value| dup_freeze(value) }.dup.freeze
      when Array
        params.map { |value| dup_freeze(value) }.dup.freeze
      when String
        params.dup.freeze
      when Symbol, NilClass, TrueClass, FalseClass, Class, Proc
        params
      else
        raise Error, "Unsupported param type #{params.inspect}"
      end
    end
```
